services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: 'start-dev --http-port 38218 --import-realm'
    volumes:
      - ./src/main/docker/realm-config:/opt/keycloak/data/import
      - ./src/main/docker/realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=38218
      - KC_HTTP_MANAGEMENT_PORT=9990
      - KC_HEALTH_ENABLED=true
    ports:
      - "127.0.0.1:38218:38218"
      - "127.0.0.1:39000:9990"
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
