management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  show-actuator: true


#----------------------------App Props---------------------------------------------#
spring:
  application:
    name: api-gateway
  profiles:
    active: #spring.profiles.active#  
    default: dev
  session:
    redis:
      namespace: mra:gateway
    timeout: 5m
  data:
    redis:
      host: localhost
      port: 50451
      connect-timeout: 2s
      timeout: 1s
  security:
    oauth2:
      client:
        registration:
          customer1:
            client-id: gateway
            client-secret: 7MY447xL4xaGMlIY7EzSgde73GF8D2gq
            scope: openid
        provider:
          customer1:
            issuerUri: ${AUTH_SERVER_URL:http://localhost:38218}/realms/customer1


#application:
#  domain: .mra.io
server:
  reactive:
    session:
      cookie:
        domain: .mra.io