server:
  port: 4000

spring:
  cloud:
    gateway:
      routes:
        - id: red-app-route
          uri: http://localhost:4200
          predicates:
            - Host=red.mra.io:4000
        - id: blue-app-route
          uri: http://localhost:50121
          predicates:
            - Host=blue.mra.io:4000
        - id: green-app-route
          uri: http://localhost:50212
          predicates:
            - Host=green.mra.io:4000
        - id: no-ops
          uri: no://op
          predicates:
            - Path=/**
          filters:
            - name: SetStatus
              args:
                status: 404
      default-filters: 
        - name: SaveSession
        - name: TokenRelay
  docker:
    compose:
      file: api-gateway/compose.yml
      start:
        skip: never
      lifecycle-management: start_only
      enabled: true

logging:
  level:
    root: DEBUG
    web: TRACE
    'dev.ubaid': DEBUG
    'org.springframework.cloud': TRACE
    'org.springframework.web': TRACE
    'org.springframework.security': TRACE
