management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  show-actuator: true


#----------------------------App Props---------------------------------------------#
spring:
  application:
    name: api-gateway
  profiles:
    active: #spring.profiles.active#  
    default: dev