apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mra
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
      nodePort: 32600
  type: NodePort
  